# This job checks that picus and the halo2 frontend without the llzk deps builds for 1.85

name: Continuous Integration (1.85)

on:
  pull_request:
  push:
    branches: 
      - main

env:
  # /opt/homebrew/opt/llvm@20/ is for macOS
  MLIR_SYS_200_PREFIX: /home/linuxbrew/.linuxbrew/opt/llvm@20/
  TABLEGEN_200_PREFIX: /home/linuxbrew/.linuxbrew/opt/llvm@20/
  RUSTFLAGS: '-L /home/linuxbrew/.linuxbrew/opt/llvm@20/lib'
  LLZK_SYS_ENABLE_WHOLE_ARCHIVE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET: 
          - release
          - dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      # - name: Free Disk Space
      #   uses: jlumbroso/free-disk-space@v1.3.1
      #   with:
      #     large-packages: false
      # - uses: Homebrew/actions/setup-homebrew@master
      # - name: Cache homebrew downloads
      #   uses: actions/cache@v4
      #   with: 
      #     path: ~/.cache/Homebrew/
      #     # It's not the greatest key in the world but works
      #     key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Cargo.lock') }}
      # - name: Install LLVM & MLIR
      #   run: brew install llvm@20
      # - run: /home/linuxbrew/.linuxbrew/opt/llvm@20/bin/llvm-config --version
      - name: Cache cargo crates
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.BUILD_TARGET }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build picus in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo +1.85.0 build -p picus --profile ${{ matrix.BUILD_TARGET }} --all-features
      - name: Run tests for picus in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo +1.85.0 test -p picus --profile ${{ matrix.BUILD_TARGET }} --all-features
      - name: Build halo2 frontend in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo +1.85.0 build -p halo2-llzk-frontend --profile ${{ matrix.BUILD_TARGET }} --no-default-features --features picus-backend
      - name: Run tests for halo2 frontend in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo +1.85.0 test -p halo2-llzk-frontend --profile ${{ matrix.BUILD_TARGET }} --no-default-features --features picus-backend

