name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  LLVM_PREFIX: /home/linuxbrew/.linuxbrew/opt/llvm@20
  # /opt/homebrew/opt/llvm@20/ is for macOS
  MLIR_SYS_200_PREFIX: ${{ env.LLVM_PREFIX }}
  TABLEGEN_200_PREFIX: ${{ env.LLVM_PREFIX }}
  RUSTFLAGS: '-L ${{ env.LLVM_PREFIX }}/lib'
  LLZK_SYS_ENABLE_WHOLE_ARCHIVE: 1

  LLVM_DIR: ${{ env.LLVM_PREFIX }}/lib/cmake/llvm
  Clang_DIR: ${{ env.LLVM_PREFIX }}/lib/cmake/clang

  CC: ${{ env.LLVM_PREFIX }}/bin/clang
  CXX: ${{ env.LLVM_PREFIX }}/bin/clang++

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        BUILD_TARGET:
          - release
          - dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Free Disk Space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          large-packages: false
      - uses: Homebrew/actions/setup-homebrew@master
      - name: Cache homebrew downloads
        uses: actions/cache@v4
        with:
          path: ~/.cache/Homebrew/
          # It's not the greatest key in the world but works
          key: ${{ runner.os }}-homebrew-${{ hashFiles('**/Cargo.lock') }}
      - name: Install LLVM & MLIR
        run: brew install llvm@20
      - run: /home/linuxbrew/.linuxbrew/opt/llvm@20/bin/llvm-config --version
      - name: Cache cargo crates
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.BUILD_TARGET }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Build in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo build --profile ${{ matrix.BUILD_TARGET }} --all-features
      - name: Run tests in "${{ matrix.BUILD_TARGET }}" mode
        run: cargo test --profile ${{ matrix.BUILD_TARGET }} --all-features
